export interface RecipeSummary {
  slug: string;
  name: string;
  description: string;
  prepTime: string;
  cookTime: string;
  difficulty: "Easy" | "Medium" | "Hard";
  tags: string[];
  gradient: string;
  emoji: string;
}

export const RECIPE_SUMMARIES: RecipeSummary[] = [
  {
    slug: "gochujang-butter-noodles",
    name: "Gochujang Butter Noodles",
    description: "Glossy, deeply spiced noodles with fermented chili heat, brown butter, and caramelised soy. One pan. Twenty minutes.",
    prepTime: "10 min",
    cookTime: "15 min",
    difficulty: "Medium",
    tags: ["spicy", "high-protein", "under-30-min", "weeknight"],
    gradient: "linear-gradient(135deg, #C0392B 0%, #E67E22 100%)",
    emoji: "🍜",
  },
  {
    slug: "dan-dan-noodles",
    name: "Dan Dan Noodles",
    description: "Sichuan street food classic — spicy sesame sauce, crispy pork mince, and bouncy wheat noodles.",
    prepTime: "15 min",
    cookTime: "15 min",
    difficulty: "Medium",
    tags: ["spicy", "high-protein"],
    gradient: "linear-gradient(135deg, #922B21 0%, #CB4335 100%)",
    emoji: "🥢",
  },
  {
    slug: "spicy-sesame-cold-noodles",
    name: "Spicy Sesame Cold Noodles",
    description: "Chilled noodles drenched in a nutty, fiery sesame sauce. The ultimate summer bowl.",
    prepTime: "10 min",
    cookTime: "5 min",
    difficulty: "Easy",
    tags: ["spicy", "vegetarian", "under-30-min"],
    gradient: "linear-gradient(135deg, #B7950B 0%, #D4AC0D 100%)",
    emoji: "🥗",
  },
  {
    slug: "beef-pho",
    name: "Beef Pho",
    description: "A deeply aromatic beef broth with star anise and charred ginger, poured over silky rice noodles.",
    prepTime: "30 min",
    cookTime: "3 hr 30 min",
    difficulty: "Hard",
    tags: ["high-protein", "meal-prep"],
    gradient: "linear-gradient(135deg, #6E2C00 0%, #A04000 100%)",
    emoji: "🍲",
  },
  {
    slug: "pad-thai",
    name: "Pad Thai",
    description: "The real deal — tamarind-forward, perfectly charred, finished with a wok's worth of flavour.",
    prepTime: "15 min",
    cookTime: "10 min",
    difficulty: "Medium",
    tags: ["high-protein", "under-30-min"],
    gradient: "linear-gradient(135deg, #D35400 0%, #E59866 100%)",
    emoji: "🥡",
  },
  {
    slug: "japchae",
    name: "Japchae",
    description: "Korean glass noodles stir-fried with shiitake mushrooms, colourful vegetables, and a sesame soy glaze.",
    prepTime: "20 min",
    cookTime: "15 min",
    difficulty: "Medium",
    tags: ["vegetarian", "meal-prep"],
    gradient: "linear-gradient(135deg, #1A5276 0%, #2471A3 100%)",
    emoji: "🫙",
  },
  {
    slug: "cold-soba-dashi",
    name: "Cold Soba with Dashi",
    description: "Buckwheat noodles served chilled with an umami-rich dashi dipping broth. Refined and effortless.",
    prepTime: "10 min",
    cookTime: "10 min",
    difficulty: "Easy",
    tags: ["vegetarian", "under-30-min"],
    gradient: "linear-gradient(135deg, #1E8449 0%, #27AE60 100%)",
    emoji: "🍃",
  },
  {
    slug: "udon-carbonara",
    name: "Udon Carbonara",
    description: "Thick, chewy udon noodles meet the silky egg-and-cheese magic of a classic carbonara.",
    prepTime: "10 min",
    cookTime: "10 min",
    difficulty: "Medium",
    tags: ["high-protein", "under-30-min"],
    gradient: "linear-gradient(135deg, #7D6608 0%, #B7950B 100%)",
    emoji: "🧀",
  },
  {
    slug: "laksa",
    name: "Laksa",
    description: "A rich, spicy coconut curry broth loaded with rice noodles, prawns, and fragrant laksa leaf.",
    prepTime: "20 min",
    cookTime: "25 min",
    difficulty: "Hard",
    tags: ["spicy", "high-protein"],
    gradient: "linear-gradient(135deg, #D4A017 0%, #E8C94F 100%)",
    emoji: "🦐",
  },
  {
    slug: "wonton-noodle-soup",
    name: "Wonton Noodle Soup",
    description: "Hand-folded pork and prawn wontons bobbing in a clear, deeply savoury broth with egg noodles.",
    prepTime: "30 min",
    cookTime: "10 min",
    difficulty: "Medium",
    tags: ["high-protein"],
    gradient: "linear-gradient(135deg, #5D6D7E 0%, #85929E 100%)",
    emoji: "🥟",
  },
  {
    slug: "garlic-lo-mein",
    name: "Garlic Ginger Lo Mein",
    description: "Takeaway-quality lo mein at home — wok-charred noodles with fragrant garlic, ginger, and soy.",
    prepTime: "10 min",
    cookTime: "10 min",
    difficulty: "Easy",
    tags: ["vegetarian", "under-30-min", "weeknight"],
    gradient: "linear-gradient(135deg, #1A5276 0%, #1ABC9C 100%)",
    emoji: "🫚",
  },
  {
    slug: "pad-see-ew",
    name: "Pad See Ew",
    description: "Wide flat rice noodles wok-fried with egg, Chinese broccoli, and dark sweet soy.",
    prepTime: "10 min",
    cookTime: "15 min",
    difficulty: "Medium",
    tags: ["high-protein", "under-30-min"],
    gradient: "linear-gradient(135deg, #212F3D 0%, #34495E 100%)",
    emoji: "🥚",
  },
  {
    slug: "mapo-tofu-noodles",
    name: "Mapo Tofu Noodles",
    description: "The numbing heat of mapo tofu poured over a tangle of thin noodles. Double the flavour.",
    prepTime: "10 min",
    cookTime: "20 min",
    difficulty: "Medium",
    tags: ["spicy", "vegetarian"],
    gradient: "linear-gradient(135deg, #78281F 0%, #C0392B 100%)",
    emoji: "🌶️",
  },
  {
    slug: "chilli-oil-noodles",
    name: "Chilli Oil Noodles",
    description: "Ten-minute noodles drowned in a garlicky, crunchy chilli oil. The simplest thing on the menu.",
    prepTime: "5 min",
    cookTime: "5 min",
    difficulty: "Easy",
    tags: ["vegan", "spicy", "under-30-min"],
    gradient: "linear-gradient(135deg, #A93226 0%, #E74C3C 100%)",
    emoji: "🔥",
  },
  {
    slug: "tonkotsu-ramen",
    name: "Tonkotsu Ramen",
    description: "Cloudy pork bone broth that took hours to build, with chashu, soft egg, and springy noodles.",
    prepTime: "30 min",
    cookTime: "3 hr 30 min",
    difficulty: "Hard",
    tags: ["high-protein", "meal-prep"],
    gradient: "linear-gradient(135deg, #F0E6D3 0%, #C8A97B 100%)",
    emoji: "🍥",
  },
  {
    slug: "bun-bo-hue",
    name: "Bún Bò Huế",
    description: "Vietnam's spiciest noodle soup — lemongrass-perfumed pork and beef broth with thick round noodles.",
    prepTime: "30 min",
    cookTime: "2 hr 30 min",
    difficulty: "Hard",
    tags: ["spicy", "high-protein"],
    gradient: "linear-gradient(135deg, #B03A2E 0%, #E74C3C 100%)",
    emoji: "🫕",
  },
  {
    slug: "thai-boat-noodles",
    name: "Thai Boat Noodles",
    description: "Dark, intensely flavoured Thai noodle soup with pork blood broth and crispy pork rinds.",
    prepTime: "20 min",
    cookTime: "40 min",
    difficulty: "Hard",
    tags: ["spicy", "high-protein"],
    gradient: "linear-gradient(135deg, #1C1917 0%, #4A235A 100%)",
    emoji: "⛵",
  },
  {
    slug: "singapore-noodles",
    name: "Singapore Noodles",
    description: "Curry-dusted rice vermicelli stir-fried with prawns, char siu, and crisp beansprouts.",
    prepTime: "10 min",
    cookTime: "10 min",
    difficulty: "Easy",
    tags: ["high-protein", "under-30-min"],
    gradient: "linear-gradient(135deg, #D4AC0D 0%, #F4D03F 100%)",
    emoji: "🍤",
  },
  {
    slug: "kimchi-butter-ramen",
    name: "Kimchi Butter Ramen",
    description: "Instant ramen elevated — kimchi, brown butter, and a runny egg transform a packet into a proper meal.",
    prepTime: "5 min",
    cookTime: "10 min",
    difficulty: "Easy",
    tags: ["spicy", "under-30-min", "weeknight"],
    gradient: "linear-gradient(135deg, #C0392B 0%, #F1948A 100%)",
    emoji: "🫙",
  },
  {
    slug: "shoyu-ramen",
    name: "Shoyu Ramen",
    description: "A clear, amber soy-based broth with chicken chashu, soft-boiled egg, and nori.",
    prepTime: "20 min",
    cookTime: "25 min",
    difficulty: "Medium",
    tags: ["high-protein"],
    gradient: "linear-gradient(135deg, #6E4B1A 0%, #A0693B 100%)",
    emoji: "🥣",
  },
];
